(() => {
  const $ = id => document.getElementById(id);
  const deep = v => JSON.parse(JSON.stringify(v));
  const money = n => `${window.STREAM_CONFIG?.currencyLabel || 'Rs'} ${Number(n || 0).toLocaleString()}`;
  const BASE_LAYOUT = window.StreamOverlayLayout.defaults();
  const STORE_TYPES='streamnest:donationTypes:v1',STORE_LAYOUTS='streamnest:studioProfileLayouts:v1',STORE_PROFILE='streamnest:activeSourceProfile:v1';
  const profiles={
    'landscape-1080':{id:'landscape-1080',name:'1080p',long:'1080p Landscape',width:1920,height:1080,use:'Standard Twitch / YouTube / Kick'},
    'landscape-2k':{id:'landscape-2k',name:'2K',long:'2K Landscape',width:2560,height:1440,use:'High-resolution landscape stream'},
    'vertical-short':{id:'vertical-short',name:'9:16',long:'Short / Vertical',width:1080,height:1920,use:'TikTok / Shorts / vertical live'}
  };
  const placements=[['top-left','↖'],['top-center','↑'],['top-right','↗'],['center-left','←'],['center-center','•'],['center-right','→'],['bottom-left','↙'],['bottom-center','↓'],['bottom-right','↘']];
  const placementNames={'top-left':'Top Left','top-center':'Top Center','top-right':'Top Right','center-left':'Center Left','center-center':'Center','center-right':'Center Right','bottom-left':'Bottom Left','bottom-center':'Bottom Center','bottom-right':'Bottom Right'};
  const sizes=[['compact','Compact'],['standard','Standard'],['large','Large'],['takeover','Takeover']];
  const impacts={
    subtle:{name:'Subtle',copy:'Small, quick, non-blocking',size:'compact',duration:3500},
    standard:{name:'Standard',copy:'Clear without hiding gameplay',size:'standard',duration:5500},
    hype:{name:'Hype',copy:'Bigger motion + longer attention',size:'large',duration:7000},
    takeover:{name:'Takeover',copy:'Full-stream premium moment',size:'takeover',duration:9000}
  };
  const stylePresets={
    clean:{name:'Clean',accent:'#ff6a1a',card:'#0c0c12',border:'#34343d',radius:30,opacity:.94},
    neon:{name:'Neon',accent:'#a55cff',card:'#100b18',border:'#7448aa',radius:26,opacity:.92},
    glass:{name:'Glass',accent:'#59c7ff',card:'#121722',border:'#445061',radius:38,opacity:.78},
    danger:{name:'Danger',accent:'#ff3d62',card:'#1a0c10',border:'#7c2638',radius:18,opacity:.96}
  };
  const templateMeta={
    support:{name:'Support + TTS',icon:'💬',description:'Viewer sends support with an optional spoken message.',kind:'support',price:500,pricingMode:'minimum',tts:true,label:'TTS SUPPORT',impact:'standard'},
    drop:{name:'Rare Drop',icon:'✨',description:'Premium animated moment with media, sound and optional TTS.',kind:'drop',price:2500,pricingMode:'fixed',tts:true,label:'RARE DROP',impact:'hype'},
    challenge:{name:'Challenge',icon:'🎯',description:'Viewer pays to activate a pre-approved stream challenge.',kind:'challenge',price:1000,pricingMode:'fixed',tts:false,label:'CHALLENGE UNLOCKED',impact:'standard'},
    jumpscare:{name:'Jumpscare',icon:'👻',description:'A fast shock visual + sound hit designed for reaction moments.',kind:'custom',price:750,pricingMode:'fixed',tts:false,label:'JUMPSCARE',impact:'hype'},
    sound:{name:'Sound Bite',icon:'🔊',description:'A short sound effect viewers can trigger instantly.',kind:'custom',price:300,pricingMode:'fixed',tts:false,label:'SOUND ALERT',impact:'subtle'},
    media:{name:'Meme Blast',icon:'🎬',description:'A GIF or short video takes over part of the stream.',kind:'custom',price:1000,pricingMode:'fixed',tts:true,label:'MEDIA ALERT',impact:'hype'},
    wheel:{name:'Spin the Wheel',icon:'🎡',description:'Viewer pays to trigger your custom wheel or random outcome.',kind:'custom',price:1500,pricingMode:'fixed',tts:false,label:'SPIN THE WHEEL',impact:'standard'},
    reward:{name:'Custom Reward',icon:'🎁',description:'Build any other paid interaction you want.',kind:'custom',price:1000,pricingMode:'fixed',tts:false,label:'STREAM REWARD',impact:'standard'}
  };

  function defaultType(id,sceneKey,template){const t=templateMeta[template]||templateMeta.reward;return{id,sceneKey,template,name:t.name,icon:t.icon,description:t.description,kind:t.kind,price:t.price,pricingMode:t.pricingMode,enabled:true,ttsEnabled:t.tts,label:t.label,impact:t.impact||'standard',stylePreset:'clean',dailyStock:0,cooldownSec:0,appearance:{accent:'#ff6a1a',text:'#ffffff',card:'#0c0c12',border:'#34343d',radius:36,opacity:.93,showIcon:true,showAmount:true,showName:true,showMessage:true},audio:{voice:window.STREAM_CONFIG?.tts?.defaultVoice||'serafina',soundUrl:'',mediaUrl:'',soundVolume:.88},motion:{enter:'pop',exit:'fade',animationMs:500,durationMs:impacts[t.impact||'standard'].duration},placements:{'landscape-1080':{position:template==='drop'?'center-center':'bottom-center',size:impacts[t.impact||'standard'].size,safe:true},'landscape-2k':{position:template==='drop'?'center-center':'bottom-center',size:impacts[t.impact||'standard'].size,safe:true},'vertical-short':{position:template==='drop'?'center-center':'bottom-center',size:template==='drop'?'large':impacts[t.impact||'standard'].size,safe:true}}};}
  function normalizeType(t){t.impact=t.impact||'standard';t.stylePreset=t.stylePreset||'clean';t.dailyStock=Number(t.dailyStock||0);t.cooldownSec=Number(t.cooldownSec||0);return t}
  function loadTypes(){try{const v=JSON.parse(localStorage.getItem(STORE_TYPES)||'null');if(Array.isArray(v)&&v.length)return v.map(normalizeType)}catch(_){}return[defaultType('support','support','support'),defaultType('drop','drop','drop'),defaultType('challenge','challenge','challenge')];}
  function scaleLayout(layout,w,h){const out=deep(layout),sx=w/out.canvas.width,sy=h/out.canvas.height;out.canvas={width:w,height:h};Object.values(out.scenes||{}).forEach(sc=>sc.elements?.forEach(el=>{el.x*=sx;el.y*=sy;el.w*=sx;el.h*=sy;el.fontSize=(el.fontSize||24)*Math.min(sx,sy);el.borderRadius=(el.borderRadius||0)*Math.min(sx,sy);el.padding=(el.padding||0)*Math.min(sx,sy)}));return out}
  function loadLayouts(){try{const v=JSON.parse(localStorage.getItem(STORE_LAYOUTS)||'null');if(v&&typeof v==='object')return v}catch(_){}return{'landscape-1080':deep(BASE_LAYOUT),'landscape-2k':scaleLayout(BASE_LAYOUT,2560,1440),'vertical-short':scaleLayout(BASE_LAYOUT,1080,1920)}}

  let types=loadTypes(),layouts=loadLayouts(),profileId=localStorage.getItem(STORE_PROFILE)||'landscape-1080',typeId=types[0]?.id||'support',selectedTemplate='jumpscare',showSafe=true,showGrid=false,typeFilter='all';if(!profiles[profileId])profileId='landscape-1080';
  const currentProfile=()=>profiles[profileId],currentType=()=>types.find(t=>t.id===typeId)||types[0],currentLayout=()=>layouts[profileId],currentScene=()=>currentLayout().scenes[currentType().sceneKey],placement=()=>currentType().placements[profileId]||(currentType().placements[profileId]={position:'bottom-center',size:'standard',safe:true});
  function toast(text){const n=$('scToast');n.textContent=text;n.classList.add('show');clearTimeout(window.__ccToast);window.__ccToast=setTimeout(()=>n.classList.remove('show'),1800)}
  function saveAll(){localStorage.setItem(STORE_TYPES,JSON.stringify(types));localStorage.setItem(STORE_LAYOUTS,JSON.stringify(layouts));localStorage.setItem(STORE_PROFILE,profileId);toast('Studio saved')}
  function ensureScene(type){for(const [pid,layout] of Object.entries(layouts)){if(layout.scenes[type.sceneKey])continue;const source=layout.scenes.support||Object.values(layout.scenes)[0],sc=deep(source);sc.name=type.name;sc.durationMs=type.motion.durationMs;layout.scenes[type.sceneKey]=sc;applyTypeStyleToLayout(type,pid);applyPlacementToLayout(type,pid,true)}}
  types.forEach(ensureScene);

  function renderProfileSelect(){const s=$('profileSelect');s.innerHTML='';Object.values(profiles).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`${p.name} · ${p.width}×${p.height}`;o.selected=p.id===profileId;s.appendChild(o)})}
  function renderTypes(){const box=$('donationTypes');box.innerHTML='';types.filter(t=>typeFilter==='all'||(typeFilter==='support'?t.kind==='support':typeFilter==='drop'?t.kind==='drop':typeFilter==='challenge'?t.kind==='challenge':t.kind==='custom')).forEach(t=>{const b=document.createElement('button');b.className=`cc-type-card ${t.id===typeId?'active':''}`;b.innerHTML=`<span class="icon">${t.icon}</span><span><b>${escapeHtml(t.name)}</b><small>${escapeHtml(t.description)}</small><span class="state ${t.enabled?'on':''}">${t.enabled?'● LIVE':'● HIDDEN'} · ${impacts[t.impact||'standard'].name}</span></span><span class="price">${t.pricingMode==='free'?'EVENT':money(t.price)}</span>`;b.onclick=()=>{typeId=t.id;renderAll()};box.appendChild(b)})}
  function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
  function renderHeader(){const p=currentProfile(),t=currentType();$('sourcePill').textContent=p.name;$('sourceResolution').textContent=`${p.width} × ${p.height}`;$('sourceUse').textContent=p.use;$('typeTitle').textContent=`${t.icon} ${t.name}`;$('typeSubtitle').textContent=t.description;$('previewHint').textContent=`${placementNames[placement().position]} · ${sizes.find(x=>x[0]===placement().size)?.[1]||'Standard'}`;$('typeStateBadge').textContent=t.enabled?'LIVE':'HIDDEN';$('typeStateBadge').classList.toggle('off',!t.enabled);renderWorth()}
  function renderWorth(){const t=currentType(),tags=[];if(t.ttsEnabled)tags.push('🔊 TTS');if(t.audio.mediaUrl)tags.push('🎬 Media');if(t.audio.soundUrl)tags.push('🔉 Sound');tags.push(`⚡ ${impacts[t.impact||'standard'].name} impact`);tags.push(`⏱ ${(t.motion.durationMs/1000).toFixed(1)}s`);if(t.dailyStock>0)tags.push(`🎟 ${t.dailyStock}/day`);$('worthHeadline').textContent=t.kind==='drop'?'A premium on-screen moment viewers can visibly own':t.kind==='challenge'?'A paid action that changes what happens on stream':t.template==='jumpscare'?'An instant reaction moment with sound + visual impact':t.template==='sound'?'A fast audio hit that chat instantly recognises':'A message that gets seen — and optionally heard';$('worthTags').innerHTML=tags.map(x=>`<span>${x}</span>`).join('')}
  function previewData(){const t=currentType();return{label:t.label,name:'ChoozaFan',amount:t.pricingMode==='free'?'DEMO':money(t.price),title:t.name,message:'“This is how the interaction feels on stream.”',icon:t.icon,ttsBadge:t.ttsEnabled?'🔊 TTS':'',dropMedia:t.audio.mediaUrl||''}}
  function roleValue(el,d){return el.role?(d[el.role]??el.text??''):(el.text||'')}
  function tMedia(){return currentType().audio.mediaUrl||''}
  function renderPreview(){const p=currentProfile(),stage=$('previewStage'),scene=currentScene(),viewport=$('previewViewport');if(!scene)return;const maxW=Math.max(280,viewport.clientWidth-40),maxH=Math.max(300,viewport.clientHeight-40),s=Math.min(maxW/p.width,maxH/p.height,.62);stage.style.width=`${p.width*s}px`;stage.style.height=`${p.height*s}px`;const root=$('previewScene');root.style.width=`${p.width}px`;root.style.height=`${p.height}px`;root.style.transform=`scale(${s})`;root.innerHTML='';const safe=$('safeArea'),m=.06;safe.hidden=!showSafe;safe.style.left=`${p.width*m*s}px`;safe.style.top=`${p.height*m*s}px`;safe.style.width=`${p.width*(1-2*m)*s}px`;safe.style.height=`${p.height*(1-2*m)*s}px`;$('previewGrid').hidden=!showGrid;const d=previewData();scene.elements.slice().sort((a,b)=>(a.z||0)-(b.z||0)).forEach(el=>{if(el.visible===false)return;const n=document.createElement('div');n.className='preview-el';Object.assign(n.style,{left:`${el.x}px`,top:`${el.y}px`,width:`${el.w}px`,height:`${el.h}px`,zIndex:el.z||1,color:el.color||'#fff',background:el.background||'transparent',border:`${el.borderWidth||0}px solid ${el.borderColor||'transparent'}`,borderRadius:`${el.borderRadius||0}px`,fontSize:`${el.fontSize||24}px`,fontWeight:el.fontWeight||700,opacity:el.opacity??1,justifyContent:el.align==='center'?'center':el.align==='right'?'flex-end':'flex-start',textAlign:el.align||'left',padding:`${el.padding||0}px`,transform:`rotate(${el.rotation||0}deg)`});if(el.type==='media'){const src=(el.role==='dropMedia'||el.role==='media')?tMedia():el.src;if(src){const media=/\.(webm|mp4|mov)(\?|$)/i.test(src)?document.createElement('video'):document.createElement('img');media.src=src;media.style.width='100%';media.style.height='100%';media.style.objectFit=el.objectFit||'contain';if(media.tagName==='VIDEO'){media.autoplay=true;media.loop=true;media.muted=true;media.playsInline=true}n.appendChild(media)}else{n.style.border='1px dashed #575c69';n.style.color='#747b8b';n.style.justifyContent='center';n.textContent='MEDIA'}}else n.textContent=roleValue(el,d);root.appendChild(n)})}

  function bounds(scene){const visible=scene.elements.filter(e=>e.visible!==false&&['static','media'].includes(e.type)||e.visible!==false);const minX=Math.min(...visible.map(e=>e.x)),minY=Math.min(...visible.map(e=>e.y)),maxX=Math.max(...visible.map(e=>e.x+e.w)),maxY=Math.max(...visible.map(e=>e.y+e.h));return{minX,minY,maxX,maxY,w:maxX-minX,h:maxY-minY}}
  function applyPlacementToLayout(type,pid,force=false){const layout=layouts[pid],scene=layout.scenes[type.sceneKey];if(!scene)return;const pl=type.placements[pid],p=profiles[pid],b=bounds(scene),sizeScale={compact:.72,standard:1,large:1.28,takeover:Math.min((p.width*.82)/Math.max(b.w,1),(p.height*.72)/Math.max(b.h,1))}[pl.size]||1;const cx=b.minX+b.w/2,cy=b.minY+b.h/2;scene.elements.forEach(el=>{if(force||!el.__quickBase)el.__quickBase={x:el.x,y:el.y,w:el.w,h:el.h,fontSize:el.fontSize||24,borderRadius:el.borderRadius||0,padding:el.padding||0};const q=el.__quickBase;el.x=cx+(q.x-cx)*sizeScale;el.y=cy+(q.y-cy)*sizeScale;el.w=q.w*sizeScale;el.h=q.h*sizeScale;el.fontSize=q.fontSize*sizeScale;el.borderRadius=q.borderRadius*sizeScale;el.padding=q.padding*sizeScale});const nb=bounds(scene),pad=pl.safe?Math.min(p.width,p.height)*.06:18,spots={'top-left':[pad,pad],'top-center':[(p.width-nb.w)/2,pad],'top-right':[p.width-pad-nb.w,pad],'center-left':[pad,(p.height-nb.h)/2],'center-center':[(p.width-nb.w)/2,(p.height-nb.h)/2],'center-right':[p.width-pad-nb.w,(p.height-nb.h)/2],'bottom-left':[pad,p.height-pad-nb.h],'bottom-center':[(p.width-nb.w)/2,p.height-pad-nb.h],'bottom-right':[p.width-pad-nb.w,p.height-pad-nb.h]},target=spots[pl.position]||spots['bottom-center'],dx=target[0]-nb.minX,dy=target[1]-nb.minY;scene.elements.forEach(el=>{el.x+=dx;el.y+=dy});scene.durationMs=type.motion.durationMs}
  function applyTypeStyleToLayout(type,pid){const sc=layouts[pid].scenes[type.sceneKey];if(!sc)return;sc.durationMs=type.motion.durationMs;sc.soundUrl=type.audio.soundUrl;sc.soundVolume=type.audio.soundVolume;sc.elements.forEach(el=>{if(el.role==='label')el.text=type.label;if(el.role==='icon')el.text=type.icon;if(el.role==='media'||el.role==='dropMedia')el.src=type.audio.mediaUrl||el.src;if(el.role==='icon')el.visible=type.appearance.showIcon;if(el.role==='amount')el.visible=type.appearance.showAmount;if(el.role==='name')el.visible=type.appearance.showName;if(el.role==='message')el.visible=type.appearance.showMessage;if(['title','label','name','amount','message','icon'].includes(el.role))el.color=type.appearance.text;if(el.role==='amount'||el.role==='label')el.color=type.appearance.accent;if(el.type==='static'){el.background=hexToRgba(type.appearance.card,type.appearance.opacity);el.borderColor=type.appearance.border;el.borderRadius=type.appearance.radius}el.enterAnimation=type.motion.enter;el.exitAnimation=type.motion.exit;el.animationMs=type.motion.animationMs})}
  function applyTypeStyle(type){Object.keys(layouts).forEach(pid=>applyTypeStyleToLayout(type,pid))}
  function hexToRgba(hex,a){const h=String(hex||'#000').replace('#','');if(!/^[0-9a-f]{6}$/i.test(h))return hex;return`rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},${a})`}

  function renderPlacement(){const pg=$('placementGrid');pg.innerHTML='';placements.forEach(([id,sym])=>{const b=document.createElement('button');b.className=`cc-place-btn ${placement().position===id?'active':''}`;b.title=placementNames[id];b.textContent=sym;b.onclick=()=>{placement().position=id;applyPlacementToLayout(currentType(),profileId);renderAll()};pg.appendChild(b)});const sc=$('sizeChoices');sc.innerHTML='';sizes.forEach(([id,label])=>{const b=document.createElement('button');b.className=placement().size===id?'active':'';b.textContent=label;b.onclick=()=>{placement().size=id;applyPlacementToLayout(currentType(),profileId);renderAll()};sc.appendChild(b)})}
  function renderImpacts(){const box=$('impactChoices');box.innerHTML='';Object.entries(impacts).forEach(([id,v])=>{const b=document.createElement('button');b.className=`cc-impact-card ${currentType().impact===id?'active':''}`;b.innerHTML=`<b>${v.name}</b><small>${v.copy}</small>`;b.onclick=()=>{const t=currentType();t.impact=id;t.motion.durationMs=v.duration;placement().size=v.size;applyPlacementToLayout(t,profileId);applyTypeStyle(t);renderAll()};box.appendChild(b)})}
  function renderStyles(){const box=$('stylePresets');box.innerHTML='';Object.entries(stylePresets).forEach(([id,v])=>{const b=document.createElement('button');b.className=`cc-style-card ${currentType().stylePreset===id?'active':''}`;b.style.setProperty('--preset',v.accent);b.innerHTML=`<b>${v.name}</b>`;b.onclick=()=>{const t=currentType();t.stylePreset=id;Object.assign(t.appearance,{accent:v.accent,card:v.card,border:v.border,radius:v.radius,opacity:v.opacity});applyTypeStyle(t);fillControls();renderStyles();renderPreview()};box.appendChild(b)})}
  function fillVoices(){const s=$('ttsVoice');s.innerHTML='';(window.STREAM_CONFIG?.tts?.voices||[]).forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=v.label||v.name||v.id;s.appendChild(o)})}
  function fillControls(){const t=currentType(),a=t.appearance,au=t.audio,m=t.motion;$('safePlacement').checked=placement().safe;$('accentColor').value=a.accent;$('textColor').value=a.text;$('cardColor').value=a.card;$('borderColor').value=a.border;$('cornerRadius').value=a.radius;$('cornerRadiusOut').textContent=`${a.radius}px`;$('cardOpacity').value=a.opacity;$('cardOpacityOut').textContent=`${Math.round(a.opacity*100)}%`;$('showIcon').checked=a.showIcon;$('showAmount').checked=a.showAmount;$('showName').checked=a.showName;$('showMessage').checked=a.showMessage;$('ttsEnabled').checked=t.ttsEnabled;$('ttsVoice').value=au.voice;$('mediaUrl').value=au.mediaUrl;$('soundUrl').value=au.soundUrl;$('soundVolume').value=au.soundVolume;$('soundVolumeOut').textContent=`${Math.round(au.soundVolume*100)}%`;$('publicName').value=t.name;$('typeDescription').value=t.description;$('typeIcon').value=t.icon;$('typeLabel').value=t.label;$('typePrice').value=t.price;$('pricingMode').value=t.pricingMode;$('dailyStock').value=t.dailyStock||0;$('cooldownSec').value=t.cooldownSec||0;$('typeEnabled').checked=t.enabled;$('enterAnimation').value=m.enter;$('exitAnimation').value=m.exit;$('animationMs').value=m.animationMs;$('animationMsOut').textContent=`${m.animationMs}ms`;$('durationMs').value=m.durationMs;$('durationMsOut').textContent=`${(m.durationMs/1000).toFixed(1)}s`}
  function renderAll(){ensureScene(currentType());applyTypeStyleToLayout(currentType(),profileId);renderProfileSelect();renderTypes();renderHeader();renderPlacement();renderImpacts();renderStyles();fillControls();renderPreview()}

  function bindTabs(){document.querySelectorAll('#configTabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#configTabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))})}
  function bindFilters(){document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));typeFilter=b.dataset.filter;renderTypes()})}
  function bindControls(){
    $('profileSelect').onchange=e=>{profileId=e.target.value;localStorage.setItem(STORE_PROFILE,profileId);ensureScene(currentType());renderAll()};
    $('safePlacement').onchange=e=>{placement().safe=e.target.checked;applyPlacementToLayout(currentType(),profileId);renderAll()};
    ['accentColor','textColor','cardColor','borderColor'].forEach(id=>$(id).oninput=e=>{const map={accentColor:'accent',textColor:'text',cardColor:'card',borderColor:'border'};currentType().appearance[map[id]]=e.target.value;currentType().stylePreset='custom';applyTypeStyle(currentType());renderPreview()});
    $('cornerRadius').oninput=e=>{currentType().appearance.radius=Number(e.target.value);$('cornerRadiusOut').textContent=`${e.target.value}px`;applyTypeStyle(currentType());renderPreview()};$('cardOpacity').oninput=e=>{currentType().appearance.opacity=Number(e.target.value);$('cardOpacityOut').textContent=`${Math.round(e.target.value*100)}%`;applyTypeStyle(currentType());renderPreview()};
    [['showIcon','showIcon'],['showAmount','showAmount'],['showName','showName'],['showMessage','showMessage']].forEach(([id,key])=>$(id).onchange=e=>{currentType().appearance[key]=e.target.checked;applyTypeStyle(currentType());renderPreview()});
    $('ttsEnabled').onchange=e=>{currentType().ttsEnabled=e.target.checked;renderWorth()};$('ttsVoice').onchange=e=>currentType().audio.voice=e.target.value;$('mediaUrl').oninput=e=>{currentType().audio.mediaUrl=e.target.value.trim();applyTypeStyle(currentType());renderWorth();renderPreview()};$('soundUrl').oninput=e=>{currentType().audio.soundUrl=e.target.value.trim();applyTypeStyle(currentType());renderWorth()};$('soundVolume').oninput=e=>{currentType().audio.soundVolume=Number(e.target.value);$('soundVolumeOut').textContent=`${Math.round(e.target.value*100)}%`;applyTypeStyle(currentType())};
    $('publicName').oninput=e=>{currentType().name=e.target.value||'Untitled';renderTypes();renderHeader()};$('typeDescription').oninput=e=>{currentType().description=e.target.value;renderTypes();renderHeader()};$('typeIcon').oninput=e=>{currentType().icon=e.target.value||'✦';applyTypeStyle(currentType());renderTypes();renderHeader();renderPreview()};$('typeLabel').oninput=e=>{currentType().label=e.target.value;applyTypeStyle(currentType());renderPreview()};$('typePrice').oninput=e=>{currentType().price=Number(e.target.value||0);renderTypes()};$('pricingMode').onchange=e=>{currentType().pricingMode=e.target.value;renderTypes()};$('dailyStock').oninput=e=>{currentType().dailyStock=Number(e.target.value||0);renderWorth()};$('cooldownSec').oninput=e=>currentType().cooldownSec=Number(e.target.value||0);$('typeEnabled').onchange=e=>{currentType().enabled=e.target.checked;renderAll()};
    $('enterAnimation').onchange=e=>{currentType().motion.enter=e.target.value;applyTypeStyle(currentType());renderPreview()};$('exitAnimation').onchange=e=>{currentType().motion.exit=e.target.value;applyTypeStyle(currentType())};$('animationMs').oninput=e=>{currentType().motion.animationMs=Number(e.target.value);$('animationMsOut').textContent=`${e.target.value}ms`;applyTypeStyle(currentType())};$('durationMs').oninput=e=>{currentType().motion.durationMs=Number(e.target.value);$('durationMsOut').textContent=`${(e.target.value/1000).toFixed(1)}s`;applyTypeStyle(currentType());renderWorth()};
    $('safeAreaBtn').onclick=()=>{showSafe=!showSafe;$('safeAreaBtn').classList.toggle('active',showSafe);renderPreview()};$('gridBtn').onclick=()=>{showGrid=!showGrid;$('gridBtn').classList.toggle('active',showGrid);renderPreview()};$('saveStudioBtn').onclick=saveAll;$('resetTypeBtn').onclick=resetCurrentType;$('testObsBtn').onclick=testInObs;$('publishObsBtn').onclick=publishToObs;$('copyObsProfileBtn').onclick=copyObsProfileUrl;
    $('navAssets').onclick=()=>{const b=document.querySelector('#configTabs [data-tab="media"]');if(b)b.click();document.getElementById('studioWork')?.scrollIntoView({behavior:'smooth',block:'start'})};$('navRules').onclick=()=>{const b=document.querySelector('#configTabs [data-tab="rules"]');if(b)b.click();document.getElementById('studioWork')?.scrollIntoView({behavior:'smooth',block:'start'})};document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'}));
  }

  function genericSceneFor(template,pid){const layout=layouts[pid];let source;if(['media','drop','jumpscare'].includes(template))source=layout.scenes.drop;else if(template==='challenge')source=layout.scenes.challenge;else source=layout.scenes.support;const sc=deep(source);if(template==='sound')sc.elements=sc.elements.filter(e=>e.type!=='media');if(['media','jumpscare'].includes(template)&&!sc.elements.some(e=>e.type==='media'))sc.elements.push({id:'media',type:'media',role:'media',x:500,y:200,w:920,h:520,z:5,visible:true,src:'',fontSize:20,fontWeight:700,color:'#fff',background:'transparent',borderColor:'transparent',borderWidth:0,borderRadius:28,opacity:1,align:'center',padding:0,objectFit:'contain'});return sc}
  function addDonationType(){const name=$('newTypeName').value.trim();if(!name)return;const template=selectedTemplate,id=`custom-${Date.now().toString(36)}`,sceneKey=id,t=defaultType(id,sceneKey,template);t.kind='custom';t.name=name;t.icon=$('newTypeIcon').value.trim()||templateMeta[template].icon;t.price=Number($('newTypePrice').value||0);t.label=name.toUpperCase();for(const pid of Object.keys(layouts))layouts[pid].scenes[sceneKey]=genericSceneFor(template,pid);types.push(t);typeId=id;applyTypeStyle(t);Object.keys(layouts).forEach(pid=>applyPlacementToLayout(t,pid,true));saveAll();renderAll();toast(`${name} added`)}
  function renderTemplates(){const box=$('templateGrid');box.innerHTML='';[['jumpscare','Jumpscare'],['sound','Sound Bite'],['media','Meme Blast'],['support','Support / TTS'],['challenge','Challenge'],['drop','Rare Drop'],['wheel','Spin the Wheel'],['reward','Custom Reward']].forEach(([id,label])=>{const t=templateMeta[id];const b=document.createElement('button');b.type='button';b.className=`cc-template-card ${selectedTemplate===id?'active':''}`;b.innerHTML=`<b>${t.icon} ${label}</b><small>${t.description}</small>`;b.onclick=()=>{selectedTemplate=id;renderTemplates();$('newTypeName').value=t.name;$('newTypeIcon').value=t.icon;$('newTypePrice').value=t.price};box.appendChild(b)})}
  function resetCurrentType(){const idx=types.findIndex(t=>t.id===typeId),old=types[idx],template=old.id==='drop'?'drop':old.id==='challenge'?'challenge':old.id==='support'?'support':old.template||'reward',fresh=defaultType(old.id,old.sceneKey,template);types[idx]=fresh;for(const pid of Object.keys(layouts)){if(['support','drop','challenge'].includes(fresh.sceneKey)){const base=pid==='landscape-1080'?deep(BASE_LAYOUT):scaleLayout(BASE_LAYOUT,profiles[pid].width,profiles[pid].height);layouts[pid].scenes[fresh.sceneKey]=base.scenes[fresh.sceneKey]}else layouts[pid].scenes[fresh.sceneKey]=genericSceneFor(fresh.template,pid);applyTypeStyleToLayout(fresh,pid);applyPlacementToLayout(fresh,pid,true)}renderAll();toast('Interaction reset')}
  function testEvent(){const t=currentType();return{verified:true,preview:true,demo:true,type:t.kind==='drop'?'drop':t.kind==='challenge'?'challenge':t.kind==='support'?'support':'custom',sceneKey:t.sceneKey,donationTypeId:t.id,name:'ChoozaFan',amount:t.price,title:t.name,message:'Testing this interaction on the live stream.',tts:t.ttsEnabled,voiceProfile:t.audio.voice,ttsProvider:(window.STREAM_CONFIG?.tts?.voices||[]).find(v=>v.id===t.audio.voice)?.provider||'browser',rarity:t.template==='drop'?'LEGENDARY':'',icon:t.icon,label:t.label,assetUrl:t.audio.mediaUrl,soundUrl:t.audio.soundUrl,soundVolume:t.audio.soundVolume}}
  function obsProfileUrl(){const u=new URL('overlay.html',location.href);u.searchParams.set('obs','1');u.searchParams.set('profile',profileId);u.searchParams.set('v',window.STREAM_CONFIG?.buildVersion||'8');return u.toString()}
  async function copyObsProfileUrl(){try{await navigator.clipboard.writeText(obsProfileUrl());toast(`OBS link copied · ${currentProfile().width}×${currentProfile().height}`)}catch(_){prompt('Copy this OBS Browser Source URL',obsProfileUrl())}}
  async function testInObs(){const btn=$('testObsBtn');btn.disabled=true;btn.textContent='Sending…';try{const result=await window.StreamPreviewTransport.send({kind:'studio-preview',profile:profileId,event:testEvent(),layout:deep(currentLayout())});toast(result.cloud?'Test sent to OBS':'Test sent locally only')}catch(e){toast(`Test failed: ${e.message||e}`)}finally{btn.disabled=false;btn.textContent='▶ Test'}}
  async function publishToObs(){saveAll();const btn=$('publishObsBtn');btn.disabled=true;btn.textContent='Publishing…';try{const result=await window.StreamPreviewTransport.send({kind:'studio-layout-sync',profile:profileId,layout:deep(currentLayout())});toast(result.cloud?`${currentProfile().long} published to OBS`:'Saved locally; cloud unavailable')}catch(e){toast(`Publish failed: ${e.message||e}`)}finally{btn.disabled=false;btn.textContent='⇧ Publish'}}
  function bindDialog(){renderTemplates();const open=()=>{$('newTypeName').value=templateMeta[selectedTemplate].name;$('newTypeIcon').value=templateMeta[selectedTemplate].icon;$('newTypePrice').value=templateMeta[selectedTemplate].price;$('addTypeDialog').showModal()};$('addTypeBtn').onclick=open;$('addTypeWideBtn').onclick=open;$('addTypeForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();addDonationType();$('addTypeDialog').close()})}
  function init(){fillVoices();bindTabs();bindFilters();bindControls();bindDialog();window.addEventListener('resize',renderPreview);renderAll()}
  init();
})();
